/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppTest2: typeof import('./../components/app-test-dir/AppTest2.vue')['default']
    FlyContent: typeof import('./../components/fly-content/fly-content.vue')['default']
    FlyHeader: typeof import('./../components/fly-header/fly-header.vue')['default']
    FlyLogin: typeof import('./../components/fly-login/fly-login.vue')['default']
    FlyNavbar: typeof import('./../components/fly-navbar/fly-navbar.vue')['default']
    NavigationBar: typeof import('./../components/navigation-bar/navigation-bar.vue')['default']
    PageHeader: typeof import('./../components/PageHeader/PageHeader.vue')['default']
    TimeSchedule: typeof import('./../components/TimeSchedule.vue')['default']
  }
}
